[project]
name = "dog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "cellpose>=3.1.0",
    "matplotlib>=3.9.4",
    "opencv-python-headless>=4.11.0.86",
    "torch>=2.5.1",
]
